name: Release
on:
  push:
    tags:
      - v*.*.*

jobs:
  # No. OS      ARCH    COMPILER
  # 14. Ubuntu  x86_64  ldc
  create-linux-x86_64:
    name: create-linux-x86_64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ldc-latest
      - name: Build bianry
        run: dub build -a=x86_64 -b=release -c=default
      - name: Generate document
        run: |
          (which dot >/dev/null 2>&1) || (sudo apt-get update && sudo apt-get install -y graphvis)
          rdmd ./scripts/runner.d -a=x86_64 --mode=generate-document
        #  dub build -b=ddeps
      - name: Upload generated pages
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: docs

  # Deploy Pages
  create-taggedpage:
    name: deploy_docs
    needs: push_check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
      # バージョン値確認
      - name: Set version
        id: set_ver
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      # ドキュメントのアーティファクトダウンロード
      - name: Download generated pages
        uses: actions/download-artifact@v2
        with:
          name: docs
          path: ${{ steps.set_ver.outputs.VERSION }}
      # キュメントをGitHub Pagesへデプロイ
      - name: Deploy pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          allow_empty_commit: false
          publish_dir: .
          publish_branch: gh-pages
          user_name: GitHub Actions Bot
          user_email: <>
